### ISSUE TITLE
Getting editor contents in an event

### ISSUE THREAD

**Issue by mbabauer** [froala/froala-reactive#9] opened 2015-01-08 23:53 UTC
I am trying to get the editor contents with straight JS in events my template.  Is there a way to get a reference to the editor this way?  

For example, I am doing this:
```
var contents = tmpl.$('#content').editable('getHTML', false, true)
```

This is obviously not working because there is no "text area".  Am I stuck using helpers and the onbeforesave?

**Comment by rjsmith** [comment] 2015-01-19 23:51
@mbabauer Please close this issue if it answers your question adequately - thanks!

**Closed** 2015-01-20 11:47 UTC

**Comment by EddyBorja** [comment] 2015-09-02 21:29
When I try to get editable, it tells me it's undefined.

**Comment by rjsmith** [comment] 2015-09-03 09:02
Hi,
You will need to provide more information, code examples etc if I am to help you out, which I am very happy to do.  What exactly are you trying to achieve? What have you already tried?

**Comment by EddyBorja** [comment] 2015-09-03 14:28
I'll try to get more info but I still can't replicate the problem in a simpler test project. Have to troubleshoot my code. All I want is to get the HTML when the user clicks a submit button. The editor itself is part of a larger form and I'm more interested in the rich editing capability than the reactive saving.

**Comment by rjsmith** [comment] 2015-09-03 14:39
OK.  You may be better off using the `meteor add froala:editor` package,
which simply provides the FE javascript plugin as a Meteor package, if you
don't need any of the reactive wrapping from froala-reactive.  Then you can
just refer to the FE docs.

https://github.com/froala/meteor-froala

**Comment by EddyBorja** [comment] 2015-09-03 14:45
Yea but that package doesn't seem to come with a template I can drop in

**Comment by EddyBorja** [comment] 2015-09-03 18:47
It looks like the problem is caused by a conflict with Bower packages installed with mquandalle:bower. Not sure what to do about this yet.
